export const TOWNS = [
["Абаза, Республика Хакасия "," Abaza, Republic of Khakassia"],
["Абакан, Республика Хакасия "," Abakan, Republic of Khakassia"],
["Абдулино, Оренбургская область "," Abdulino, Orenburg Oblast"],
["Абинск, Краснодарский край "," Abinsk, Krasnodar Krai"],
["Агидель, Республика Башкортостан "," Agidel, Republic of Bashkortostan"],
["Агрыз, Республика Татарстан "," Agryz, Republic of Tatarstan"],
["Адыгейск, Республика Адыгея "," Adygeysk, Republic of Adygea"],
["Азнакаево, Республика Татарстан "," Aznakayevo, Republic of Tatarstan"],
["Азов, Ростовская область "," Azov, Rostov Oblast"],
["Ак-Довурак, Республика Тыва "," Ak-Dovurak, Tuva Republic"],
["Аксай, Ростовская область "," Aksay, Rostov Oblast"],
["Алагир, Республика Северная Осетия — Алания "," Alagir, Republic of North Ossetia-Alania"],
["Алапаевск, Свердловская область "," Alapayevsk, Sverdlovsk Oblast"],
["Алатырь, Чувашская Республика "," Alatyr, Chuvash Republic"],
["Алдан, Республика Саха "," Aldan, Sakha Republic"],
["Алейск, Алтайский край "," Aleysk, Altai Krai"],
["Александров, Владимирская область "," Alexandrov, Vladimir Oblast"],
["Александровск, Пермский край "," Alexandrovsk, Perm Krai"],
["Александровск-Сахалинский, Сахалинская область "," Alexandrovsk-Sakhalinsky, Sakhalin Oblast"],
["Алексеевка, Белгородская область "," Alexeyevka, Belgorod Oblast"],
["Алексин, Тульская область "," Aleksin, Tula Oblast"],
["Алзамай, Иркутская область "," Alzamay, Irkutsk Oblast"],
["Алупка, Республика Крым "," Alupka, Republic of Crimea"],
["Алушта, Республика Крым "," Alushta, Republic of Crimea"],
["Альметьевск, Республика Татарстан "," Almetyevsk, Republic of Tatarstan"],
["Амурск, Хабаровский край "," Amursk, Khabarovsk Krai"],
["Анадырь, Чукотский автономный округ "," Anadyr, Chukotka Autonomous Okrug"],
["Анапа, Краснодарский край "," Anapa, Krasnodar Krai"],
["Ангарск, Иркутская область "," Angarsk, Irkutsk Oblast"],
["Андреаполь, Тверская область "," Andreapol, Tver Oblast"],
["Анжеро-Судженск, Кемеровская область "," Anzhero-Sudzhensk, Kemerovo Oblast"],
["Анива, Сахалинская область "," Aniva, Sakhalin Oblast"],
["Апатиты, Мурманская область "," Apatity, Murmansk Oblast"],
["Апрелевка, Московская область "," Aprelevka, Moscow Oblast"],
["Апшеронск, Краснодарский край "," Apsheronsk, Krasnodar Krai"],
["Арамиль, Свердловская область "," Aramil, Sverdlovsk Oblast"],
["Аргун, Чеченская Республика "," Argun, Chechen Republic"],
["Ардатов, Республика Мордовия "," Ardatov, Republic of Mordovia"],
["Ардон, Республика Северная Осетия — Алания "," Ardon, Republic of North Ossetia-Alania"],
["Арзамас, Нижегородская область "," Arzamas, Nizhny Novgorod Oblast"],
["Аркадак, Саратовская область "," Arkadak, Saratov Oblast"],
["Армавир, Краснодарский край "," Armavir, Krasnodar Krai"],
["Армянск, Республика Крым "," Armyansk, Republic of Crimea"],
["Арсеньев, Приморский край "," Arsenyev, Primorsky Krai"],
["Арск, Республика Татарстан "," Arsk, Republic of Tatarstan"],
["Артём, Приморский край "," Artyom, Primorsky Krai"],
["Артёмовск, Красноярский край "," Artyomovsk, Krasnoyarsk Krai"],
["Артёмовский, Свердловская область "," Artyomovsky, Sverdlovsk Oblast"],
["Архангельск, Архангельская область "," Arkhangelsk, Arkhangelsk Oblast"],
["Асбест, Свердловская область "," Asbest, Sverdlovsk Oblast"],
["Асино, Томская область "," Asino, Tomsk Oblast"],
["Астрахань, Астраханская область "," Astrakhan, Astrakhan Oblast"],
["Аткарск, Саратовская область "," Atkarsk, Saratov Oblast"],
["Ахтубинск, Астраханская область "," Akhtubinsk, Astrakhan Oblast"],
["Ачинск, Красноярский край "," Achinsk, Krasnoyarsk Krai"],
["Аша, Челябинская область "," Asha, Chelyabinsk Oblast"],
["ББабаево, Вологодская область "," Babayevo, Vologda Oblast"],
["Бабушкин, Республика Бурятия "," Babushkin, Republic of Buryatia"],
["Бавлы, Республика Татарстан "," Bavly, Republic of Tatarstan"],
["Багратионовск, Калининградская область "," Bagrationovsk, Kaliningrad Oblast"],
["Байкальск, Иркутская область "," Baykalsk, Irkutsk Oblast"],
["Баймак, Республика Башкортостан "," Baymak, Republic of Bashkortostan"],
["Бакал, Челябинская область "," Bakal, Chelyabinsk Oblast"],
["Баксан, Кабардино-Балкарская Республика "," Baksan, Kabardino-Balkar Republic"],
["Балабаново, Калужская область "," Balabanovo, Kaluga Oblast"],
["Балаково, Саратовская область "," Balakovo, Saratov Oblast"],
["Балахна, Нижегородская область "," Balakhna, Nizhny Novgorod Oblast"],
["Балашиха, Московская область "," Balashikha, Moscow Oblast"],
["Балашов, Саратовская область "," Balashov, Saratov Oblast"],
["Балей, Забайкальский край "," Baley, Zabaykalsky Krai"],
["Балтийск, Калининградская область "," Baltiysk, Kaliningrad Oblast"],
["Барабинск, Новосибирская область "," Barabinsk, Novosibirsk Oblast"],
["Барнаул, Алтайский край "," Barnaul, Altai Krai"],
["Барыш, Ульяновская область "," Barysh, Ulyanovsk Oblast"],
["Батайск, Ростовская область "," Bataysk, Rostov Oblast"],
["Бахчисарай, Республика Крым "," Bakhchysarai, Republic of Crimea"],
["Бежецк, Тверская область "," Bezhetsk, Tver Oblast"],
["Белая Калитва, Ростовская область "," Belaya Kalitva, Rostov Oblast"],
["Белая Холуница, Кировская область "," Belaya Kholunitsa, Kirov Oblast"],
["Белгород, Белгородская область "," Belgorod, Belgorod Oblast"],
["Белебей, Республика Башкортостан "," Belebey, Republic of Bashkortostan"],
["Белёв, Тульская область "," Belyov, Tula Oblast"],
["Белинский, Пензенская область "," Belinsky, Penza Oblast"],
["Белово, Кемеровская область "," Belovo, Kemerovo Oblast"],
["Белогорск, Амурская область "," Belogorsk, Amur Oblast"],
["Белогорск, Республика Крым "," Bilohirsk, Republic of Crimea"],
["Белозерск, Вологодская область "," Belozersk, Vologda Oblast"],
["Белокуриха, Алтайский край "," Belokurikha, Altai Krai"],
["Беломорск, Республика Карелия "," Belomorsk, Republic of Karelia"],
["Белорецк, Республика Башкортостан "," Beloretsk, Republic of Bashkortostan"],
["Белореченск, Краснодарский край "," Belorechensk, Krasnodar Krai"],
["Белоусово, Калужская область "," Belousovo, Kaluga Oblast"],
["Белоярский, Ханты-Мансийский автономный округ "," Beloyarsky, Khanty-Mansi Autonomous Okrug"],
["Белый, Тверская область "," Bely, Tver Oblast"],
["Бердск, Новосибирская область "," Berdsk, Novosibirsk Oblast"],
["Березники, Пермский край "," Berezniki, Perm Krai"],
["Берёзовский, Кемеровская область "," Beryozovsky, Kemerovo Oblast"],
["Берёзовский, Свердловская область "," Beryozovsky, Sverdlovsk Oblast"],
["Беслан, Республика Северная Осетия — Алания "," Beslan, Republic of North Ossetia-Alania"],
["Бийск, Алтайский край "," Biysk, Altai Krai"],
["Бикин, Хабаровский край "," Bikin, Khabarovsk Krai"],
["Билибино, Чукотский автономный округ "," Bilibino, Chukotka Autonomous Okrug"],
["Биробиджан, Еврейская автономная область "," Birobidzhan, Jewish Autonomous Oblast"],
["Бирск, Республика Башкортостан "," Birsk, Republic of Bashkortostan"],
["Бирюсинск, Иркутская область "," Biryusinsk, Irkutsk Oblast"],
["Бирюч, Белгородская область "," Biryuch, Belgorod Oblast"],
["Благовещенск, Республика Башкортостан "," Blagoveshchensk, Republic of Bashkortostan"],
["Благовещенск, Амурская область "," Blagoveshchensk, Amur Oblast"],
["Благодарный, Ставропольский край "," Blagodarny, Stavropol Krai"],
["Бобров, Воронежская область "," Bobrov, Voronezh Oblast"],
["Богданович, Свердловская область "," Bogdanovich, Sverdlovsk Oblast"],
["Богородицк, Тульская область "," Bogoroditsk, Tula Oblast"],
["Богородск, Нижегородская область "," Bogorodsk, Nizhny Novgorod Oblast"],
["Боготол, Красноярский край "," Bogotol, Krasnoyarsk Krai"],
["Богучар, Воронежская область "," Boguchar, Voronezh Oblast"],
["Бодайбо, Иркутская область "," Bodaybo, Irkutsk Oblast"],
["Бокситогорск, Ленинградская область "," Boksitogorsk, Leningrad Oblast"],
["Болгар, Республика Татарстан "," Bolgar, Republic of Tatarstan"],
["Бологое, Тверская область "," Bologoye, Tver Oblast"],
["Болотное, Новосибирская область "," Bolotnoye, Novosibirsk Oblast"],
["Болохово, Тульская область "," Bolokhovo, Tula Oblast"],
["Болхов, Орловская область "," Bolkhov, Oryol Oblast"],
["Большой Камень, Приморский край "," Bolshoy Kamen, Primorsky Krai"],
["Бор, Нижегородская область "," Bor, Nizhny Novgorod Oblast"],
["Борзя, Забайкальский край "," Borzya, Zabaykalsky Krai"],
["Борисоглебск, Воронежская область "," Borisoglebsk, Voronezh Oblast"],
["Боровичи, Новгородская область "," Borovichi, Novgorod Oblast"],
["Боровск, Калужская область "," Borovsk, Kaluga Oblast"],
["Бородино, Красноярский край "," Borodino, Krasnoyarsk Krai"],
["Братск, Иркутская область "," Bratsk, Irkutsk Oblast"],
["Бронницы, Московская область "," Bronnitsy, Moscow Oblast"],
["Брянск, Брянская область "," Bryansk, Bryansk Oblast"],
["Бугульма, Республика Татарстан "," Bugulma, Republic of Tatarstan"],
["Бугуруслан, Оренбургская область "," Buguruslan, Orenburg Oblast"],
["Будённовск, Ставропольский край "," Budyonnovsk, Stavropol Krai"],
["Бузулук, Оренбургская область "," Buzuluk, Orenburg Oblast"],
["Буинск, Республика Татарстан "," Buinsk, Republic of Tatarstan"],
["Буй, Костромская область "," Buy, Kostroma Oblast"],
["Буйнакск, Республика Дагестан "," Buynaksk, Republic of Dagestan"],
["Бутурлиновка, Воронежская область "," Buturlinovka, Voronezh Oblast"],
["ВВалдай, Новгородская область "," Valday, Novgorod Oblast"],
["Валуйки, Белгородская область "," Valuyki, Belgorod Oblast"],
["Велиж, Смоленская область "," Velizh, Smolensk Oblast"],
["Великие Луки, Псковская область "," Velikiye Luki, Pskov Oblast"],
["Великий Новгород, Новгородская область "," Veliky Novgorod, Novgorod Oblast"],
["Великий Устюг, Вологодская область "," Veliky Ustyug, Vologda Oblast"],
["Вельск, Архангельская область "," Velsk, Arkhangelsk Oblast"],
["Венёв, Тульская область "," Venyov, Tula Oblast"],
["Верещагино, Пермский край "," Vereshchagino, Perm Krai"],
["Верея, Московская область "," Vereya, Moscow Oblast"],
["Верхнеуральск, Челябинская область "," Verkhneuralsk, Chelyabinsk Oblast"],
["Верхний Тагил, Свердловская область "," Verkhny Tagil, Sverdlovsk Oblast"],
["Верхний Уфалей, Челябинская область "," Verkhny Ufaley, Chelyabinsk Oblast"],
["Верхняя Пышма, Свердловская область "," Verkhnyaya Pyshma, Sverdlovsk Oblast"],
["Верхняя Салда, Свердловская область "," Verkhnyaya Salda, Sverdlovsk Oblast"],
["Верхняя Тура, Свердловская область "," Verkhnyaya Tura, Sverdlovsk Oblast"],
["Верхотурье, Свердловская область "," Verkhoturye, Sverdlovsk Oblast"],
["Верхоянск, Республика Саха "," Verkhoyansk, Sakha Republic"],
["Весьегонск, Тверская область "," Vesyegonsk, Tver Oblast"],
["Ветлуга, Нижегородская область "," Vetluga, Nizhny Novgorod Oblast"],
["Видное, Московская область "," Vidnoye, Moscow Oblast"],
["Вилюйск, Республика Саха "," Vilyuysk, Sakha Republic"],
["Вилючинск, Камчатский край "," Vilyuchinsk, Kamchatka Krai"],
["Вихоревка, Иркутская область "," Vikhorevka, Irkutsk Oblast"],
["Вичуга, Ивановская область "," Vichuga, Ivanovo Oblast"],
["Владивосток, Приморский край "," Vladivostok, Primorsky Krai"],
["Владикавказ, Республика Северная Осетия — Алания "," Vladikavkaz, Republic of North Ossetia-Alania"],
["Владимир, Владимирская область "," Vladimir, Vladimir Oblast"],
["Волгоград, Волгоградская область "," Volgograd, Volgograd Oblast"],
["Волгодонск, Ростовская область "," Volgodonsk, Rostov Oblast"],
["Волгореченск, Костромская область "," Volgorechensk, Kostroma Oblast"],
["Волжск, Республика Марий Эл "," Volzhsk, Mari El Republic"],
["Волжский, Волгоградская область "," Volzhsky, Volgograd Oblast"],
["Вологда, Вологодская область "," Vologda, Vologda Oblast"],
["Володарск, Нижегородская область "," Volodarsk, Nizhny Novgorod Oblast"],
["Волоколамск, Московская область "," Volokolamsk, Moscow Oblast"],
["Волосово, Ленинградская область "," Volosovo, Leningrad Oblast"],
["Волхов, Ленинградская область "," Volkhov, Leningrad Oblast"],
["Волчанск, Свердловская область "," Volchansk, Sverdlovsk Oblast"],
["Вольск, Саратовская область "," Volsk, Saratov Oblast"],
["Воркута, Республика Коми "," Vorkuta, Komi Republic"],
["Воронеж, Воронежская область "," Voronezh, Voronezh Oblast"],
["Ворсма, Нижегородская область "," Vorsma, Nizhny Novgorod Oblast"],
["Воскресенск, Московская область "," Voskresensk, Moscow Oblast"],
["Воткинск, Удмуртская Республика "," Votkinsk, Udmurt Republic"],
["Всеволожск, Ленинградская область "," Vsevolozhsk, Leningrad Oblast"],
["Вуктыл, Республика Коми "," Vuktyl, Komi Republic"],
["Выборг, Ленинградская область "," Vyborg, Leningrad Oblast"],
["Выкса, Нижегородская область "," Vyksa, Nizhny Novgorod Oblast"],
["Высоковск, Московская область "," Vysokovsk, Moscow Oblast"],
["Высоцк, Ленинградская область "," Vysotsk, Leningrad Oblast"],
["Вытегра, Вологодская область "," Vytegra, Vologda Oblast"],
["Вышний Волочёк, Тверская область "," Vyshny Volochyok, Tver Oblast"],
["Вяземский, Хабаровский край "," Vyazemsky, Khabarovsk Krai"],
["Вязники, Владимирская область "," Vyazniki, Vladimir Oblast"],
["Вязьма, Смоленская область "," Vyazma, Smolensk Oblast"],
["Вятские Поляны, Кировская область "," Vyatskiye Polyany, Kirov Oblast"],
["ГГаврилов Посад, Ивановская область "," Gavrilov Posad, Ivanovo Oblast"],
["Гаврилов-Ям, Ярославская область "," Gavrilov-Yam, Yaroslavl Oblast"],
["Гагарин, Смоленская область "," Gagarin, Smolensk Oblast"],
["Гаджиево, Мурманская область "," Gadzhiyevo, Murmansk Oblast"],
["Гай, Оренбургская область "," Gay, Orenburg Oblast"],
["Галич, Костромская область "," Galich, Kostroma Oblast"],
["Гатчина, Ленинградская область "," Gatchina, Leningrad Oblast"],
["Гвардейск, Калининградская область "," Gvardeysk, Kaliningrad Oblast"],
["Гдов, Псковская область "," Gdov, Pskov Oblast"],
["Геленджик, Краснодарский край "," Gelendzhik, Krasnodar Krai"],
["Георгиевск, Ставропольский край "," Georgiyevsk, Stavropol Krai"],
["Глазов, Удмуртская Республика "," Glazov, Udmurt Republic"],
["Голицыно, Московская область "," Golitsyno, Moscow Oblast"],
["Горбатов, Нижегородская область "," Gorbatov, Nizhny Novgorod Oblast"],
["Горно-Алтайск, Республика Алтай "," Gorno-Altaysk, Altai Republic"],
["Горнозаводск, Пермский край "," Gornozavodsk, Perm Krai"],
["Горняк, Алтайский край "," Gornyak, Altai Krai"],
["Городец, Нижегородская область "," Gorodets, Nizhny Novgorod Oblast"],
["Городище, Пензенская область "," Gorodishche, Penza Oblast"],
["Городовиковск, Республика Калмыкия "," Gorodovikovsk, Republic of Kalmykia"],
["Гороховец, Владимирская область "," Gorokhovets, Vladimir Oblast"],
["Горячий Ключ, Краснодарский край "," Goryachy Klyuch, Krasnodar Krai"],
["Грайворон, Белгородская область "," Grayvoron, Belgorod Oblast"],
["Гремячинск, Пермский край "," Gremyachinsk, Perm Krai"],
["Грозный, Чеченская Республика "," Grozny, Chechen Republic"],
["Грязи, Липецкая область "," Gryazi, Lipetsk Oblast"],
["Грязовец, Вологодская область "," Gryazovets, Vologda Oblast"],
["Губаха, Пермский край "," Gubakha, Perm Krai"],
["Губкин, Белгородская область "," Gubkin, Belgorod Oblast"],
["Губкинский, Ямало-Ненецкий автономный округ "," Gubkinsky, Yamalo-Nenets Autonomous Okrug"],
["Гудермес, Чеченская Республика "," Gudermes, Chechen Republic"],
["Гуково, Ростовская область "," Gukovo, Rostov Oblast"],
["Гулькевичи, Краснодарский край "," Gulkevichi, Krasnodar Krai"],
["Гурьевск, Калининградская область "," Guryevsk, Kaliningrad Oblast"],
["Гурьевск, Кемеровская область "," Guryevsk, Kemerovo Oblast"],
["Гусев, Калининградская область "," Gusev, Kaliningrad Oblast"],
["Гусиноозёрск, Республика Бурятия "," Gusinoozyorsk, Republic of Buryatia"],
["Гусь-Хрустальный, Владимирская область "," Gus-Khrustalny, Vladimir Oblast"],
["ДДавлеканово, Республика Башкортостан "," Davlekanovo, Republic of Bashkortostan"],
["Дагестанские Огни, Республика Дагестан "," Dagestanskiye Ogni, Republic of Dagestan"],
["Далматово, Курганская область "," Dalmatovo, Kurgan Oblast"],
["Дальнегорск, Приморский край "," Dalnegorsk, Primorsky Krai"],
["Дальнереченск, Приморский край "," Dalnerechensk, Primorsky Krai"],
["Данилов, Ярославская область "," Danilov, Yaroslavl Oblast"],
["Данков, Липецкая область "," Dankov, Lipetsk Oblast"],
["Дегтярск, Свердловская область "," Degtyarsk, Sverdlovsk Oblast"],
["Дедовск, Московская область "," Dedovsk, Moscow Oblast"],
["Демидов, Смоленская область "," Demidov, Smolensk Oblast"],
["Дербент, Республика Дагестан "," Derbent, Republic of Dagestan"],
["Десногорск, Смоленская область "," Desnogorsk, Smolensk Oblast"],
["Джанкой, Республика Крым "," Dzhankoy, Republic of Crimea"],
["Дзержинск, Нижегородская область "," Dzerzhinsk, Nizhny Novgorod Oblast"],
["Дзержинский, Московская область "," Dzerzhinsky, Moscow Oblast"],
["Дивногорск, Красноярский край "," Divnogorsk, Krasnoyarsk Krai"],
["Дигора, Республика Северная Осетия — Алания "," Digora, Republic of North Ossetia-Alania"],
["Димитровград, Ульяновская область "," Dimitrovgrad, Ulyanovsk Oblast"],
["Дмитриев, Курская область "," Dmitriyev, Kursk Oblast"],
["Дмитров, Московская область "," Dmitrov, Moscow Oblast"],
["Дмитровск, Орловская область "," Dmitrovsk, Oryol Oblast"],
["Дно, Псковская область "," Dno, Pskov Oblast"],
["Добрянка, Пермский край "," Dobryanka, Perm Krai"],
["Долгопрудный, Московская область "," Dolgoprudny, Moscow Oblast"],
["Долинск, Сахалинская область "," Dolinsk, Sakhalin Oblast"],
["Домодедово, Московская область "," Domodedovo, Moscow Oblast"],
["Донецк, Ростовская область "," Donetsk, Rostov Oblast"],
["Донской, Тульская область "," Donskoy, Tula Oblast"],
["Дорогобуж, Смоленская область "," Dorogobuzh, Smolensk Oblast"],
["Дрезна, Московская область "," Drezna, Moscow Oblast"],
["Дубна, Московская область "," Dubna, Moscow Oblast"],
["Дубовка, Волгоградская область "," Dubovka, Volgograd Oblast"],
["Дудинка, Красноярский край "," Dudinka, Krasnoyarsk Krai"],
["Духовщина, Смоленская область "," Dukhovshchina, Smolensk Oblast"],
["Дюртюли, Республика Башкортостан "," Dyurtyuli, Republic of Bashkortostan"],
["Дятьково, Брянская область "," Dyatkovo, Bryansk Oblast"],
["ЕЕвпатория, Республика Крым "," Yevpatoria, Republic of Crimea"],
["Егорьевск, Московская область "," Yegoryevsk, Moscow Oblast"],
["Ейск, Краснодарский край "," Yeysk, Krasnodar Krai"],
["Екатеринбург, Свердловская область "," Yekaterinburg, Sverdlovsk Oblast"],
["Елабуга, Республика Татарстан "," Yelabuga, Republic of Tatarstan"],
["Елец, Липецкая область "," Yelets, Lipetsk Oblast"],
["Елизово, Камчатский край "," Yelizovo, Kamchatka Krai"],
["Ельня, Смоленская область "," Yelnya, Smolensk Oblast"],
["Еманжелинск, Челябинская область "," Yemanzhelinsk, Chelyabinsk Oblast"],
["Емва, Республика Коми "," Yemva, Komi Republic"],
["Енисейск, Красноярский край "," Yeniseysk, Krasnoyarsk Krai"],
["Ермолино, Калужская область "," Yermolino, Kaluga Oblast"],
["Ершов, Саратовская область "," Yershov, Saratov Oblast"],
["Ессентуки, Ставропольский край "," Yessentuki, Stavropol Krai"],
["Ефремов, Тульская область "," Yefremov, Tula Oblast"],
["ЖЖелезноводск, Ставропольский край "," Zheleznovodsk, Stavropol Krai"],
["Железногорск, Красноярский край "," Zheleznogorsk, Krasnoyarsk Krai"],
["Железногорск, Курская область "," Zheleznogorsk, Kursk Oblast"],
["Железногорск-Илимский, Иркутская область "," Zheleznogorsk-Ilimsky, Irkutsk Oblast"],
["Жердевка, Тамбовская область "," Zherdevka, Tambov Oblast"],
["Жигулёвск, Самарская область "," Zhigulyovsk, Samara Oblast"],
["Жиздра, Калужская область "," Zhizdra, Kaluga Oblast"],
["Жирновск, Волгоградская область "," Zhirnovsk, Volgograd Oblast"],
["Жуков, Калужская область "," Zhukov, Kaluga Oblast"],
["Жуковка, Брянская область "," Zhukovka, Bryansk Oblast"],
["Жуковский, Московская область "," Zhukovsky, Moscow Oblast"],
["ЗЗавитинск, Амурская область "," Zavitinsk, Amur Oblast"],
["Заводоуковск, Тюменская область "," Zavodoukovsk, Tyumen Oblast"],
["Заволжск, Ивановская область "," Zavolzhsk, Ivanovo Oblast"],
["Заволжье, Нижегородская область "," Zavolzhye, Nizhny Novgorod Oblast"],
["Задонск, Липецкая область "," Zadonsk, Lipetsk Oblast"],
["Заинск, Республика Татарстан "," Zainsk, Republic of Tatarstan"],
["Закаменск, Республика Бурятия "," Zakamensk, Republic of Buryatia"],
["Заозёрный, Красноярский край "," Zaozyorny, Krasnoyarsk Krai"],
["Заозёрск, Мурманская область "," Zaozyorsk, Murmansk Oblast"],
["Западная Двина, Тверская область "," Zapadnaya Dvina, Tver Oblast"],
["Заполярный, Мурманская область "," Zapolyarny, Murmansk Oblast"],
["Зарайск, Московская область "," Zaraysk, Moscow Oblast"],
["Заречный, Пензенская область "," Zarechny, Penza Oblast"],
["Заречный, Свердловская область "," Zarechny, Sverdlovsk Oblast"],
["Заринск, Алтайский край "," Zarinsk, Altai Krai"],
["Звенигово, Республика Марий Эл "," Zvenigovo, Mari El Republic"],
["Звенигород, Московская область "," Zvenigorod, Moscow Oblast"],
["Зверево, Ростовская область "," Zverevo, Rostov Oblast"],
["Зеленогорск, Красноярский край "," Zelenogorsk, Krasnoyarsk Krai"],
["Зеленоградск, Калининградская область "," Zelenogradsk, Kaliningrad Oblast"],
["Зеленодольск, Республика Татарстан "," Zelenodolsk, Republic of Tatarstan"],
["Зеленокумск, Ставропольский край "," Zelenokumsk, Stavropol Krai"],
["Зерноград, Ростовская область "," Zernograd, Rostov Oblast"],
["Зея, Амурская область "," Zeya, Amur Oblast"],
["Зима, Иркутская область "," Zima, Irkutsk Oblast"],
["Златоуст, Челябинская область "," Zlatoust, Chelyabinsk Oblast"],
["Злынка, Брянская область "," Zlynka, Bryansk Oblast"],
["Змеиногорск, Алтайский край "," Zmeinogorsk, Altai Krai"],
["Знаменск, Астраханская область "," Znamensk, Astrakhan Oblast"],
["Зубцов, Тверская область "," Zubtsov, Tver Oblast"],
["Зуевка, Кировская область "," Zuyevka, Kirov Oblast"],
["И,ЙИвангород, Ленинградская область "," Ivangorod, Leningrad Oblast"],
["Иваново, Ивановская область "," Ivanovo, Ivanovo Oblast"],
["Ивантеевка, Московская область "," Ivanteyevka, Moscow Oblast"],
["Ивдель, Свердловская область "," Ivdel, Sverdlovsk Oblast"],
["Игарка, Красноярский край "," Igarka, Krasnoyarsk Krai"],
["Ижевск, Удмуртская Республика "," Izhevsk, Udmurt Republic"],
["Избербаш, Республика Дагестан "," Izberbash, Republic of Dagestan"],
["Изобильный, Ставропольский край "," Izobilny, Stavropol Krai"],
["Иланский, Красноярский край "," Ilansky, Krasnoyarsk Krai"],
["Инза, Ульяновская область "," Inza, Ulyanovsk Oblast"],
["Инкерман, Севастополь "," Inkerman, Sevastopol (для посольства США — страна Украина)"],
["Иннополис, Республика Татарстан "," Innopolis, Republic of Tatarstan"],
["Инсар, Республика Мордовия "," Insar, Republic of Mordovia"],
["Инта, Республика Коми "," Inta, Komi Republic"],
["Ипатово, Ставропольский край "," Ipatovo, Stavropol Krai"],
["Ирбит, Свердловская область "," Irbit, Sverdlovsk Oblast"],
["Иркутск, Иркутская область "," Irkutsk, Irkutsk Oblast"],
["Исилькуль, Омская область "," Isilkul, Omsk Oblast"],
["Искитим, Новосибирская область "," Iskitim, Novosibirsk Oblast"],
["Истра, Московская область "," Istra, Moscow Oblast"],
["Ишим, Тюменская область "," Ishim, Tyumen Oblast"],
["Ишимбай, Республика Башкортостан "," Ishimbay, Republic of Bashkortostan"],
["Йошкар-Ола, Республика Марий Эл "," Mari El, Mari El Republic"],

["ККадников, Вологодская область "," Kadnikov, Vologda Oblast"],
["Казань, Республика Татарстан "," Kazan, Republic of Tatarstan"],
["Калач, Воронежская область "," Kalach, Voronezh Oblast"],
["Калач-на-Дону, Волгоградская область "," Kalach-na-Donu, Volgograd Oblast"],
["Калачинск, Омская область "," Kalachinsk, Omsk Oblast"],
["Калининград, Калининградская область "," Kaliningrad, Kaliningrad Oblast"],
["Калининск, Саратовская область "," Kalininsk, Saratov Oblast"],
["Калтан, Кемеровская область "," Kaltan, Kemerovo Oblast"],
["Калуга, Калужская область "," Kaluga, Kaluga Oblast"],
["Калязин, Тверская область "," Kalyazin, Tver Oblast"],
["Камбарка, Удмуртская Республика "," Kambarka, Udmurt Republic"],
["Каменка, Пензенская область "," Kamenka, Penza Oblast"],
["Каменногорск, Ленинградская область "," Kamennogorsk, Leningrad Oblast"],
["Каменск-Уральский, Свердловская область "," Kamensk-Uralsky, Sverdlovsk Oblast"],
["Каменск-Шахтинский, Ростовская область "," Kamensk-Shakhtinsky, Rostov Oblast"],
["Камень-на-Оби, Алтайский край "," Kamen-na-Obi, Altai Krai"],
["Камешково, Владимирская область "," Kameshkovo, Vladimir Oblast"],
["Камызяк, Астраханская область "," Kamyzyak, Astrakhan Oblast"],
["Камышин, Волгоградская область "," Kamyshin, Volgograd Oblast"],
["Камышлов, Свердловская область "," Kamyshlov, Sverdlovsk Oblast"],
["Канаш, Чувашская Республика "," Kanash, Chuvash Republic"],
["Кандалакша, Мурманская область "," Kandalaksha, Murmansk Oblast"],
["Канск, Красноярский край "," Kansk, Krasnoyarsk Krai"],
["Карабаново, Владимирская область "," Karabanovo, Vladimir Oblast"],
["Карабаш, Челябинская область "," Karabash, Chelyabinsk Oblast"],
["Карабулак, Республика Ингушетия "," Karabulak, Republic of Ingushetia"],
["Карасук, Новосибирская область "," Karasuk, Novosibirsk Oblast"],
["Карачаевск, Карачаево-Черкесская Республика "," Karachayevsk, Karachay-Cherkess Republic"],
["Карачев, Брянская область "," Karachev, Bryansk Oblast"],
["Каргат, Новосибирская область "," Kargat, Novosibirsk Oblast"],
["Каргополь, Архангельская область "," Kargopol, Arkhangelsk Oblast"],
["Карпинск, Свердловская область "," Karpinsk, Sverdlovsk Oblast"],
["Карталы, Челябинская область "," Kartaly, Chelyabinsk Oblast"],
["Касимов, Рязанская область "," Kasimov, Ryazan Oblast"],
["Касли, Челябинская область "," Kasli, Chelyabinsk Oblast"],
["Каспийск, Республика Дагестан "," Kaspiysk, Republic of Dagestan"],
["Катав-Ивановск, Челябинская область "," Katav-Ivanovsk, Chelyabinsk Oblast"],
["Катайск, Курганская область "," Kataysk, Kurgan Oblast"],
["Качканар, Свердловская область "," Kachkanar, Sverdlovsk Oblast"],
["Кашин, Тверская область "," Kashin, Tver Oblast"],
["Кашира, Московская область "," Kashira, Moscow Oblast"],
["Кедровый, Томская область "," Kedrovy, Tomsk Oblast"],
["Кемерово, Кемеровская область "," Kemerovo, Kemerovo Oblast"],
["Кемь, Республика Карелия "," Kem, Republic of Karelia"],
["Керчь, Республика Крым "," Kerch, Republic of Crimea (для посольства США — страна Украина)"],
["Кизел, Пермский край "," Kizel, Perm Krai"],
["Кизилюрт, Республика Дагестан "," Kizilyurt, Republic of Dagestan"],
["Кизляр, Республика Дагестан "," Kizlyar, Republic of Dagestan"],
["Кимовск, Тульская область "," Kimovsk, Tula Oblast"],
["Кимры, Тверская область "," Kimry, Tver Oblast"],
["Кингисепп, Ленинградская область "," Kingisepp, Leningrad Oblast"],
["Кинель, Самарская область "," Kinel, Samara Oblast"],
["Кинешма, Ивановская область "," Kineshma, Ivanovo Oblast"],
["Киреевск, Тульская область "," Kireyevsk, Tula Oblast"],
["Киренск, Иркутская область "," Kirensk, Irkutsk Oblast"],
["Киржач, Владимирская область "," Kirzhach, Vladimir Oblast"],
["Кириллов, Вологодская область "," Kirillov, Vologda Oblast"],
["Кириши, Ленинградская область "," Kirishi, Leningrad Oblast"],
["Киров, Калужская область "," Kirov, Kaluga Oblast"],
["Киров, Кировская область "," Kirov, Kirov Oblast"],
["Кировград, Свердловская область "," Kirovgrad, Sverdlovsk Oblast"],
["Кирово-Чепецк, Кировская область "," Kirovo-Chepetsk, Kirov Oblast"],
["Кировск, Ленинградская область "," Kirovsk, Leningrad Oblast"],
["Кировск, Мурманская область "," Kirovsk, Murmansk Oblast"],
["Кирс, Кировская область "," Kirs, Kirov Oblast"],
["Кирсанов, Тамбовская область "," Kirsanov, Tambov Oblast"],
["Киселёвск, Кемеровская область "," Kiselyovsk, Kemerovo Oblast"],
["Кисловодск, Ставропольский край "," Kislovodsk, Stavropol Krai"],
["Клин, Московская область "," Klin, Moscow Oblast"],
["Клинцы, Брянская область "," Klintsy, Bryansk Oblast"],
["Княгинино, Нижегородская область "," Knyaginino, Nizhny Novgorod Oblast"],
["Ковдор, Мурманская область "," Kovdor, Murmansk Oblast"],
["Ковров, Владимирская область "," Kovrov, Vladimir Oblast"],
["Ковылкино, Республика Мордовия "," Kovylkino, Republic of Mordovia"],
["Когалым, Ханты-Мансийский автономный округ — Югра "," Kogalym, Khanty-Mansi Autonomous Okrug"],
["Кодинск, Красноярский край "," Kodinsk, Krasnoyarsk Krai"],
["Козельск, Калужская область "," Kozelsk, Kaluga Oblast"],
["Козловка, Чувашская Республика "," Kozlovka, Chuvash Republic"],
["Козьмодемьянск, Республика Марий Эл "," Kozmodemyansk, Mari El Republic"],
["Кола, Мурманская область "," Kola, Murmansk Oblast"],
["Кологрив, Костромская область "," Kologriv, Kostroma Oblast"],
["Коломна, Московская область "," Kolomna, Moscow Oblast"],
["Колпашево, Томская область "," Kolpashevo, Tomsk Oblast"],
["Кольчугино, Владимирская область "," Kolchugino, Vladimir Oblast"],
["Коммунар, Ленинградская область "," Kommunar, Leningrad Oblast"],
["Комсомольск, Ивановская область "," Komsomolsk, Ivanovo Oblast"],
["Комсомольск-на-Амуре, Хабаровский край "," Komsomolsk-on-Amur, Khabarovsk Krai"],
["Конаково, Тверская область "," Konakovo, Tver Oblast"],
["Кондопога, Республика Карелия "," Kondopoga, Republic of Karelia"],
["Кондрово, Калужская область "," Kondrovo, Kaluga Oblast"],
["Константиновск, Ростовская область "," Konstantinovsk, Rostov Oblast"],
["Копейск, Челябинская область "," Kopeysk, Chelyabinsk Oblast"],
["Кораблино, Рязанская область "," Korablino, Ryazan Oblast"],
["Кореновск, Краснодарский край "," Korenovsk, Krasnodar Krai"],
["Коркино, Челябинская область "," Korkino, Chelyabinsk Oblast"],
["Королёв, Московская область "," Korolev, Moscow Oblast"],
["Короча, Белгородская область "," Korocha, Belgorod Oblast"],
["Корсаков, Сахалинская область "," Korsakov, Sakhalin Oblast"],
["Коряжма, Архангельская область "," Koryazhma, Arkhangelsk Oblast"],
["Костерёво, Владимирская область "," Kosteryovo, Vladimir Oblast"],
["Костомукша, Республика Карелия "," Kostomuksha, Republic of Karelia"],
["Кострома, Костромская область "," Kostroma, Kostroma Oblast"],
["Котельники, Московская область "," Kotelniki, Moscow Oblast"],
["Котельниково, Волгоградская область "," Kotelnikovo, Volgograd Oblast"],
["Котельнич, Кировская область "," Kotelnich, Kirov Oblast"],
["Котлас, Архангельская область "," Kotlas, Arkhangelsk Oblast"],
["Котово, Волгоградская область "," Kotovo, Volgograd Oblast"],
["Котовск, Тамбовская область "," Kotovsk, Tambov Oblast"],
["Кохма, Ивановская область "," Kokhma, Ivanovo Oblast"],
["Красавино, Вологодская область "," Krasavino, Vologda Oblast"],
["Красноармейск, Московская область "," Krasnoarmeysk, Moscow Oblast"],
["Красноармейск, Саратовская область "," Krasnoarmeysk, Saratov Oblast"],
["Красновишерск, Пермский край "," Krasnovishersk, Perm Krai"],
["Красногорск, Московская область "," Krasnogorsk, Moscow Oblast"],
["Краснодар, Краснодарский край "," Krasnodar, Krasnodar Krai"],
["Краснозаводск, Московская область "," Krasnozavodsk, Moscow Oblast"],
["Краснознаменск, Калининградская область "," Krasnoznamensk, Kaliningrad Oblast"],
["Краснознаменск, Московская область "," Krasnoznamensk, Moscow Oblast"],
["Краснокаменск, Забайкальский край "," Krasnokamensk, Zabaykalsky Krai"],
["Краснокамск, Пермский край "," Krasnokamsk, Perm Krai"],
["Красноперекопск, Республика Крым "," Krasnoperekopsk, Republic of Crimea (для посольства США — страна Украина)"],
["Краснослободск, Волгоградская область "," Krasnoslobodsk, Volgograd Oblast"],
["Краснослободск, Республика Мордовия "," Krasnoslobodsk, Republic of Mordovia"],
["Краснотурьинск, Свердловская область "," Krasnoturyinsk, Sverdlovsk Oblast"],
["Красноуральск, Свердловская область "," Krasnouralsk, Sverdlovsk Oblast"],
["Красноуфимск, Свердловская область "," Krasnoufimsk, Sverdlovsk Oblast"],
["Красноярск, Красноярский край "," Krasnoyarsk, Krasnoyarsk Krai"],
["Красный Кут, Саратовская область "," Krasny Kut, Saratov Oblast"],
["Красный Сулин, Ростовская область "," Krasny Sulin, Rostov Oblast"],
["Красный Холм, Тверская область "," Krasny Kholm, Tver Oblast"],
["Кремёнки, Калужская область "," Kremyonki, Kaluga Oblast"],
["Кропоткин, Краснодарский край "," Kropotkin, Krasnodar Krai"],
["Крым, Республика Крым "," Crimea, Republic of Crimea (для посольства США — страна Украина)"],
["Крымск, Краснодарский край "," Krymsk, Krasnodar Krai"],
["Кстово, Нижегородская область "," Kstovo, Nizhny Novgorod Oblast"],
["Кубинка, Московская область "," Kubinka, Moscow Oblast"],
["Кувандык, Оренбургская область "," Kuvandyk, Orenburg Oblast"],
["Кувшиново, Тверская область "," Kuvshinovo, Tver Oblast"],
["Кудымкар, Пермский край "," Kudymkar, Perm Krai"],
["Кузнецк, Пензенская область "," Kuznetsk, Penza Oblast"],
["Куйбышев, Новосибирская область "," Kuybyshev, Novosibirsk Oblast"],
["Кулебаки, Нижегородская область "," Kulebaki, Nizhny Novgorod Oblast"],
["Кумертау, Республика Башкортостан "," Kumertau, Republic of Bashkortostan"],
["Кунгур, Пермский край "," Kungur, Perm Krai"],
["Купино, Новосибирская область "," Kupino, Novosibirsk Oblast"],
["Курган, Курганская область "," Kurgan, Kurgan Oblast"],
["Курганинск, Краснодарский край "," Kurganinsk, Krasnodar Krai"],
["Курильск, Сахалинская область "," Kurilsk, Sakhalin Oblast"],
["Курлово, Владимирская область "," Kurlovo, Vladimir Oblast"],
["Куровское, Московская область "," Kurovskoye, Moscow Oblast"],
["Курск, Курская область "," Kursk, Kursk Oblast"],
["Куртамыш, Курганская область "," Kurtamysh, Kurgan Oblast"],
["Курчатов, Курская область "," Kurchatov, Kursk Oblast"],
["Куса, Челябинская область "," Kusa, Chelyabinsk Oblast"],
["Кушва, Свердловская область "," Kushva, Sverdlovsk Oblast"],
["Кызыл, Республика Тыва "," Kyzyl, Tyva Republic"],
["Кыштым, Челябинская область "," Kyshtym, Chelyabinsk Oblast"],
["Кяхта, Республика Бурятия "," Kyakhta, Republic of Buryatia"],
["ЛЛабинск, Краснодарский край "," Labinsk, Krasnodar Krai"],
["Лабытнанги, Ямало-Ненецкий автономный округ "," Labytnangi, Yamalo-Nenets Autonomous Okrug"],
["Лагань, Республика Калмыкия "," Lagan, Republic of Kalmykia"],
["Ладушкин, Калининградская область "," Ladushkin, Kaliningrad Oblast"],
["Лаишево, Республика Татарстан "," Laishevo, Republic of Tatarstan"],
["Лакинск, Владимирская область "," Lakinsk, Vladimir Oblast"],
["Лангепас, Ханты-Мансийский автономный округ — Югра "," Langepas, Khanty-Mansi Autonomous Okrug"],
["Лахденпохья, Республика Карелия "," Lakhdenpokhya, Republic of Karelia"],
["Лебедянь, Липецкая область "," Lebedyan, Lipetsk Oblast"],
["Лениногорск, Республика Татарстан "," Leninogorsk, Republic of Tatarstan"],
["Ленинск, Волгоградская область "," Leninsk, Volgograd Oblast"],
["Ленинск-Кузнецкий, Кемеровская область "," Leninsk-Kuznetsky, Kemerovo Oblast"],
["Ленск, Республика Саха "," Lensk, Sakha Republic"],
["Лермонтов, Ставропольский край "," Lermontov, Stavropol Krai"],
["Лесной, Свердловская область "," Lesnoy, Sverdlovsk Oblast"],
["Лесозаводск, Приморский край "," Lesozavodsk, Primorsky Krai"],
["Лесосибирск, Красноярский край "," Lesosibirsk, Krasnoyarsk Krai"],
["Ливны, Орловская область "," Livny, Oryol Oblast"],
["Липецк, Липецкая область "," Lipetsk, Lipetsk Oblast"],
["Ликино-Дулёво, Московская область "," Likino-Dulyovo, Moscow Oblast"],
["Липки, Тульская область "," Lipki, Tula Oblast"],
["Лиски, Воронежская область "," Liski, Voronezh Oblast"],
["Лихославль, Тверская область "," Likhoslavl, Tver Oblast"],
["Лобня, Московская область "," Lobnya, Moscow Oblast"],
["Лодейное Поле, Ленинградская область "," Lodeynoye Pole, Leningrad Oblast"],
["Лосино-Петровский, Московская область "," Losino-Petrovsky, Moscow Oblast"],
["Луга, Ленинградская область "," Luga, Leningrad Oblast"],
["Луза, Кировская область "," Luza, Kirov Oblast"],
["Лукоянов, Нижегородская область "," Lukoyanov, Nizhny Novgorod Oblast"],
["Луховицы, Московская область "," Lukhovitsy, Moscow Oblast"],
["Лысково, Нижегородская область "," Lyskovo, Nizhny Novgorod Oblast"],
["Лысьва, Пермский край "," Lysva, Perm Krai"],
["Лыткарино, Московская область "," Lytkarino, Moscow Oblast"],
["Льгов, Курская область "," Lgov, Kursk Oblast"],
["Любань, Ленинградская область "," Lyuban, Leningrad Oblast"],
["Люберцы, Московская область "," Lyubertsy, Moscow Oblast"],
["Любим, Ярославская область "," Lyubim, Yaroslavl Oblast"],
["Людиново, Калужская область "," Lyudinovo, Kaluga Oblast"],
["Лянтор, Ханты-Мансийский автономный округ — Югра "," Lyantor, Khanty-Mansi Autonomous Okrug"],
["ММагадан, Магаданская область "," Magadan, Magadan Oblast"],
["Магас, Республика Ингушетия "," Magas, Republic of Ingushetia"],
["Магнитогорск, Челябинская область "," Magnitogorsk, Chelyabinsk Oblast"],
["Майкоп, Республика Адыгея "," Maykop, Republic of Adygea"],
["Майский, Кабардино-Балкарская Республика "," Maysky, Kabardino-Balkar Republic"],
["Макаров, Сахалинская область "," Makarov, Sakhalin Oblast"],
["Макарьев, Костромская область "," Makaryev, Kostroma Oblast"],
["Макушино, Курганская область "," Makushino, Kurgan Oblast"],
["Малая Вишера, Новгородская область "," Malaya Vishera, Novgorod Oblast"],
["Малгобек, Республика Ингушетия "," Malgobek, Republic of Ingushetia"],
["Малмыж, Кировская область "," Malmyzh, Kirov Oblast"],
["Малоархангельск, Орловская область "," Maloarkhangelsk, Oryol Oblast"],
["Малоярославец, Калужская область "," Maloyaroslavets, Kaluga Oblast"],
["Мамадыш, Республика Татарстан "," Mamadysh, Republic of Tatarstan"],
["Мамоново, Калининградская область "," Mamonovo, Kaliningrad Oblast"],
["Мантурово, Костромская область "," Manturovo, Kostroma Oblast"],
["Мариинск, Кемеровская область "," Mariinsk, Kemerovo Oblast"],
["Мариинский Посад, Чувашская Республика "," Mariinsky Posad, Chuvash Republic"],
["Маркс, Саратовская область "," Marks, Saratov Oblast"],
["Махачкала, Республика Дагестан "," Makhachkala, Republic of Dagestan"],
["Мглин, Брянская область "," Mglin, Bryansk Oblast"],
["Мегион, Ханты-Мансийский автономный округ "," Megion, Khanty-Mansi Autonomous Okrug"],
["Медвежьегорск, Республика Карелия "," Medvezhyegorsk, Republic of Karelia"],
["Медногорск, Оренбургская область "," Mednogorsk, Orenburg Oblast"],
["Медынь, Калужская область "," Medyn, Kaluga Oblast"],
["Межгорье, Республика Башкортостан "," Mezhgorye, Republic of Bashkortostan"],
["Междуреченск, Кемеровская область "," Mezhdurechensk, Kemerovo Oblast"],
["Мезень, Архангельская область "," Mezen, Arkhangelsk Oblast"],
["Меленки, Владимирская область "," Melenki, Vladimir Oblast"],
["Мелеуз, Республика Башкортостан "," Meleuz, Republic of Bashkortostan"],
["Менделеевск, Республика Татарстан "," Mendeleyevsk, Republic of Tatarstan"],
["Мензелинск, Республика Татарстан "," Menzelinsk, Republic of Tatarstan"],
["Мещовск, Калужская область "," Meshchovsk, Kaluga Oblast"],
["Миасс, Челябинская область "," Miass, Chelyabinsk Oblast"],
["Микунь, Республика Коми "," Mikun, Komi Republic"],
["Миллерово, Ростовская область "," Millerovo, Rostov Oblast"],
["Минеральные Воды, Ставропольский край "," Mineralnye Vody, Stavropol Krai"],
["Минусинск, Красноярский край "," Minusinsk, Krasnoyarsk Krai"],
["Миньяр, Челябинская область "," Minyar, Chelyabinsk Oblast"],
["Мирный, Республика Саха "," Mirny, Sakha Republic"],
["Мирный, Архангельская область "," Mirny, Arkhangelsk Oblast"],
["Михайлов, Рязанская область "," Mikhaylov, Ryazan Oblast"],
["Михайловка, Волгоградская область "," Mikhaylovka, Volgograd Oblast"],
["Михайловск, Свердловская область "," Mikhaylovsk, Sverdlovsk Oblast"],
["Михайловск, Ставропольский край "," Mikhaylovsk, Stavropol Krai"],
["Мичуринск, Тамбовская область "," Michurinsk, Tambov Oblast"],
["Могоча, Забайкальский край "," Mogocha, Zabaykalsky Krai"],
["Можайск, Московская область "," Mozhaysk, Moscow Oblast"],
["Можга, Удмуртская Республика "," Mozhga, Udmurt Republic"],
["Моздок, Республика Северная Осетия — Алания "," Mozdok, Republic of North Ossetia-Alania"],
["Мончегорск, Мурманская область "," Monchegorsk, Murmansk Oblast"],
["Морозовск, Ростовская область "," Morozovsk, Rostov Oblast"],
["Моршанск, Тамбовская область "," Morshansk, Tambov Oblast"],
["Мосальск, Калужская область "," Mosalsk, Kaluga Oblast"],
["Москва "," Moscow"],
["Муравленко, Ямало-Ненецкий автономный округ "," Muravlenko, Yamalo-Nenets Autonomous Okrug"],
["Мураши, Кировская область "," Murashi, Kirov Oblast"],
["Мурманск, Мурманская область "," Murmansk, Murmansk Oblast"],
["Муром, Владимирская область "," Murom, Vladimir Oblast"],
["Мценск, Орловская область "," Mtsensk, Oryol Oblast"],
["Мыски, Кемеровская область "," Myski, Kemerovo Oblast"],
["Мытищи, Московская область "," Mytishchi, Moscow Oblast"],
["Мышкин, Ярославская область "," Myshkin, Yaroslavl Oblast"],
["ННабережные Челны, Республика Татарстан "," Naberezhnye Chelny, Republic of Tatarstan"],
["Навашино, Нижегородская область "," Navashino, Nizhny Novgorod Oblast"],
["Наволоки, Ивановская область "," Navoloki, Ivanovo Oblast"],
["Надым, Ямало-Ненецкий автономный округ "," Nadym, Yamalo-Nenets Autonomous Okrug"],
["Назарово, Красноярский край"," Nazarovo, Krasnoyarsk Krai"],
["Назрань, Республика Ингушетия "," Nazran, Republic of Ingushetia"],
["Называевск, Омская область "," Nazyvayevsk, Omsk Oblast"],
["Нальчик, Кабардино-Балкарская Республика "," Nalchik, Kabardino-Balkar Republic"],
["Нариманов, Астраханская область "," Narimanov, Astrakhan Oblast"],
["Наро-Фоминск, Московская область "," Naro-Fominsk, Moscow Oblast"],
["Нарткала, Кабардино-Балкарская Республика "," Nartkala, Kabardino-Balkar Republic"],
["Нарьян-Мар, Ненецкий автономный округ "," Naryan-Mar, Nenets Autonomous Okrug"],
["Находка, Приморский край "," Nakhodka, Primorsky Krai"],
["Невель, Псковская область "," Nevel, Pskov Oblast"],
["Невельск, Сахалинская область "," Nevelsk, Sakhalin Oblast"],
["Невинномысск, Ставропольский край "," Nevinnomyssk, Stavropol Krai"],
["Невьянск, Свердловская область "," Nevyansk, Sverdlovsk Oblast"],
["Нелидово, Тверская область "," Nelidovo, Tver Oblast"],
["Неман, Калининградская область "," Neman, Kaliningrad Oblast"],
["Нерехта, Костромская область "," Nerekhta, Kostroma Oblast"],
["Нерчинск, Забайкальский край "," Nerchinsk, Zabaykalsky Krai"],
["Нерюнгри, Республика Саха "," Neryungri, Sakha Republic"],
["Нестеров, Калининградская область "," Nesterov, Kaliningrad Oblast"],
["Нефтегорск, Самарская область "," Neftegorsk, Samara Oblast"],
["Нефтекамск, Республика Башкортостан "," Neftekamsk, Republic of Bashkortostan"],
["Нефтекумск, Ставропольский край "," Neftekumsk, Stavropol Krai"],
["Нефтеюганск, Ханты-Мансийский автономный округ "," Nefteyugansk, Khanty-Mansi Autonomous Okrug"],
["Нея, Костромская область "," Neya, Kostroma Oblast"],
["Нижневартовск, Ханты-Мансийский автономный округ "," Nizhnevartovsk, Khanty-Mansi Autonomous Okrug"],
["Нижнекамск, Республика Татарстан "," Nizhnekamsk, Republic of Tatarstan"],
["Нижнеудинск, Иркутская область "," Nizhneudinsk, Irkutsk Oblast"],
["Нижние Серги, Свердловская область "," Nizhniye Sergi, Sverdlovsk Oblast"],
["Нижний Ломов, Пензенская область "," Nizhny Lomov, Penza Oblast"],
["Нижний Новгород, Нижегородская область "," Nizhny Novgorod, Nizhny Novgorod Oblast"],
["Нижний Тагил, Свердловская область "," Nizhny Tagil, Sverdlovsk Oblast"],
["Нижняя Салда, Свердловская область "," Nizhnyaya Salda, Sverdlovsk Oblast"],
["Нижняя Тура, Свердловская область "," Nizhnyaya Tura, Sverdlovsk Oblast"],
["Николаевск, Волгоградская область "," Nikolayevsk, Volgograd Oblast"],
["Николаевск-на-Амуре, Хабаровский край "," Nikolayevsk-on-Amur, Khabarovsk Krai"],
["Никольск, Вологодская область "," Nikolsk, Vologda Oblast"],
["Никольск, Пензенская область "," Nikolsk, Penza Oblast"],
["Никольское, Ленинградская область "," Nikolskoye, Leningrad Oblast"],
["Новая Ладога, Ленинградская область "," Novaya Ladoga, Leningrad Oblast"],
["Новая Ляля, Свердловская область "," Novaya Lyalya, Sverdlovsk Oblast"],
["Новоалександровск, Ставропольский край "," Novoalexandrovsk, Stavropol Krai"],
["Новоалтайск, Алтайский край "," Novoaltaysk, Altai Krai"],
["Новоаннинский, Волгоградская область "," Novoanninsky, Volgograd Oblast"],
["Нововоронеж, Воронежская область "," Novovoronezh, Voronezh Oblast"],
["Новодвинск, Архангельская область "," Novodvinsk, Arkhangelsk Oblast"],
["Новозыбков, Брянская область "," Novozybkov, Bryansk Oblast"],
["Новокубанск, Краснодарский край "," Novokubansk, Krasnodar Krai"],
["Новокузнецк, Кемеровская область "," Novokuznetsk, Kemerovo Oblast"],
["Новокуйбышевск, Самарская область "," Novokuybyshevsk, Samara Oblast"],
["Новомичуринск, Рязанская область "," Novomichurinsk, Ryazan Oblast"],
["Новомосковск, Тульская область "," Novomoskovsk, Tula Oblast"],
["Новопавловск, Ставропольский край "," Novopavlovsk, Stavropol Krai"],
["Новоржев, Псковская область "," Novorzhev, Pskov Oblast"],
["Новороссийск, Краснодарский край "," Novorossiysk, Krasnodar Krai"],
["Новосибирск, Новосибирская область "," Novosibirsk, Novosibirsk Oblast"],
["Новосиль, Орловская область "," Novosil, Oryol Oblast"],
["Новосокольники, Псковская область "," Novosokolniki, Pskov Oblast"],
["Новотроицк, Оренбургская область "," Novotroitsk, Orenburg Oblast"],
["Новоузенск, Саратовская область "," Novouzensk, Saratov Oblast"],
["Новоульяновск, Ульяновская область "," Novoulyanovsk, Ulyanovsk Oblast"],
["Новоуральск, Свердловская область "," Novouralsk, Sverdlovsk Oblast"],
["Новохопёрск, Воронежская область "," Novokhopyorsk, Voronezh Oblast"],
["Новочебоксарск, Чувашская Республика "," Novocheboksarsk, Chuvash Republic"],
["Новочеркасск, Ростовская область "," Novocherkassk, Rostov Oblast"],
["Новошахтинск, Ростовская область "," Novoshakhtinsk, Rostov Oblast"],
["Новый Оскол, Белгородская область "," Novy Oskol, Belgorod Oblast"],
["Новый Уренгой, Ямало-Ненецкий автономный округ "," Novy Urengoy, Yamalo-Nenets Autonomous Okrug"],
["Ногинск, Московская область "," Noginsk, Moscow Oblast"],
["Нолинск, Кировская область "," Nolinsk, Kirov Oblast"],
["Норильск, Красноярский край "," Norilsk, Krasnoyarsk Krai"],
["Ноябрьск, Ямало-Ненецкий автономный округ "," Noyabrsk, Yamalo-Nenets Autonomous Okrug"],
["Нурлат, Республика Татарстан "," Nurlat, Republic of Tatarstan"],
["Нытва, Пермский край "," Nytva, Perm Krai"],
["Нюрба, Республика Саха "," Nyurba, Sakha Republic"],
["Нягань, Ханты-Мансийский автономный округ "," Nyagan, Khanty-Mansi Autonomous Okrug"],
["Нязепетровск, Челябинская область "," Nyazepetrovsk, Chelyabinsk Oblast"],
["Няндома, Архангельская область "," Nyandoma, Arkhangelsk Oblast"],
["ООблучье, Еврейская автономная область "," Obluchye, Jewish Autonomous Oblast"],
["Обнинск, Калужская область "," Obninsk, Kaluga Oblast"],
["Обоянь, Курская область "," Oboyan, Kursk Oblast"],
["Обь, Новосибирская область "," Ob, Novosibirsk Oblast"],
["Одинцово, Московская область "," Odintsovo, Moscow Oblast"],
["Озёрск, Калининградская область "," Ozyorsk, Kaliningrad Oblast"],
["Озёрск, Челябинская область "," Ozyorsk, Chelyabinsk Oblast"],
["Озёры, Московская область "," Ozyory, Moscow Oblast"],
["Октябрьск, Самарская область "," Oktyabrsk, Samara Oblast"],
["Октябрьский, Республика Башкортостан "," Oktyabrsky, Republic of Bashkortostan"],
["Окуловка, Новгородская область "," Okulovka, Novgorod Oblast"],
["Олёкминск, Республика Саха "," Olyokminsk, Sakha Republic"],
["Оленегорск, Мурманская область "," Olenegorsk, Murmansk Oblast"],
["Олонец, Республика Карелия "," Olonets, Republic of Karelia"],
["Омск, Омская область "," Omsk, Omsk Oblast"],
["Омутнинск, Кировская область "," Omutninsk, Kirov Oblast"],
["Онега, Архангельская область "," Onega, Arkhangelsk Oblast"],
["Опочка, Псковская область "," Opochka, Pskov Oblast"],
["Орёл, Орловская область "," Oryol, Oryol Oblast"],
["Оренбург, Оренбургская область "," Orenburg, Orenburg Oblast"],
["Орехово-Зуево, Московская область "," Orekhovo-Zuyevo, Moscow Oblast"],
["Орлов, Кировская область "," Orlov, Kirov Oblast"],
["Орск, Оренбургская область "," Orsk, Orenburg Oblast"],
["Оса, Пермский край "," Osa, Perm Krai"],
["Осинники, Кемеровская область "," Osinniki, Kemerovo Oblast"],
["Осташков, Тверская область "," Ostashkov, Tver Oblast"],
["Остров, Псковская область "," Ostrov, Pskov Oblast"],
["Островной, Мурманская область "," Ostrovnoy, Murmansk Oblast"],
["Острогожск, Воронежская область "," Ostrogozhsk, Voronezh Oblast"],
["Отрадное, Ленинградская область "," Otradnoye, Leningrad Oblast"],
["Отрадный, Самарская область "," Otradny, Samara Oblast"],
["Оха, Сахалинская область "," Okha, Sakhalin Oblast"],
["Оханск, Пермский край "," Okhansk, Perm Krai"],
["Очёр, Пермский край "," Ochyor, Perm Krai"],
["ППавлово, Нижегородская область "," Pavlovo, Nizhny Novgorod Oblast"],
["Павловск, Воронежская область "," Pavlovsk, Voronezh Oblast"],
["Павловский Посад, Московская область "," Pavlovsky Posad, Moscow Oblast"],
["Палласовка, Волгоградская область "," Pallasovka, Volgograd Oblast"],
["Партизанск, Приморский край "," Partizansk, Primorsky Krai"],
["Певек, Чукотский автономный округ "," Pevek, Chukotka Autonomous Okrug"],
["Пенза, Пензенская область "," Penza, Penza Oblast"],
["Первомайск, Нижегородская область "," Pervomaysk, Nizhny Novgorod Oblast"],
["Первоуральск, Свердловская область "," Pervouralsk, Sverdlovsk Oblast"],
["Перевоз, Нижегородская область "," Perevoz, Nizhny Novgorod Oblast"],
["Пересвет, Московская область "," Peresvet, Moscow Oblast"],
["Переславль-Залесский, Ярославская область "," Pereslavl-Zalessky, Yaroslavl Oblast"],
["Пермь, Пермский край "," Perm, Perm Krai"],
["Пестово, Новгородская область "," Pestovo, Novgorod Oblast"],
["Петров Вал, Волгоградская область "," Petrov Val, Volgograd Oblast"],
["Петровск, Саратовская область "," Petrovsk, Saratov Oblast"],
["Петровск-Забайкальский, Забайкальский край "," Petrovsk-Zabaykalsky, Zabaykalsky Krai"],
["Петрозаводск, Республика Карелия "," Petrozavodsk, Republic of Karelia"],
["Петропавловск-Камчатский, Камчатский край "," Petropavlovsk-Kamchatsky, Kamchatka Krai"],
["Петухово, Курганская область "," Petukhovo, Kurgan Oblast"],
["Петушки, Владимирская область "," Petushki, Vladimir Oblast"],
["Печора, Республика Коми "," Pechora, Komi Republic"],
["Печоры, Псковская область "," Pechory, Pskov Oblast"],
["Пикалёво, Ленинградская область "," Pikalyovo, Leningrad Oblast"],
["Пионерский, Калининградская область "," Pionersky, Kaliningrad Oblast"],
["Питкяранта, Республика Карелия "," Pitkyaranta, Republic of Karelia"],
["Плавск, Тульская область "," Plavsk, Tula Oblast"],
["Пласт, Челябинская область "," Plast, Chelyabinsk Oblast"],
["Плёс, Ивановская область "," Plyos, Ivanovo Oblast"],
["Поворино, Воронежская область "," Povorino, Voronezh Oblast"],
["Подольск, Московская область "," Podolsk, Moscow Oblast"],
["Подпорожье, Ленинградская область "," Podporozhye, Leningrad Oblast"],
["Покачи, Ханты-Мансийский автономный округ "," Pokachi, Khanty-Mansi Autonomous Okrug"],
["Покров, Владимирская область "," Pokrov, Vladimir Oblast"],
["Покровск, Республика Саха "," Pokrovsk, Sakha Republic"],
["Полевской, Свердловская область "," Polevskoy, Sverdlovsk Oblast"],
["Полесск, Калининградская область "," Polessk, Kaliningrad Oblast"],
["Полысаево, Кемеровская область "," Polysayevo, Kemerovo Oblast"],
["Полярные Зори, Мурманская область "," Polyarnye Zori, Murmansk Oblast"],
["Полярный, Мурманская область "," Polyarny, Murmansk Oblast"],
["Поронайск, Сахалинская область "," Poronaysk, Sakhalin Oblast"],
["Порхов, Псковская область "," Porkhov, Pskov Oblast"],
["Похвистнево, Самарская область "," Pokhvistnevo, Samara Oblast"],
["Почеп, Брянская область "," Pochep, Bryansk Oblast"],
["Починок, Смоленская область "," Pochinok, Pochinkovsky District, Smolensk Oblast"],
["Пошехонье, Ярославская область "," Poshekhonye, Yaroslavl Oblast"],
["Правдинск, Калининградская область "," Pravdinsk, Kaliningrad Oblast"],
["Приволжск, Ивановская область "," Privolzhsk, Ivanovo Oblast"],
["Приморск, Калининградская область "," Primorsk, Kaliningrad Oblast"],
["Приморск, Ленинградская область "," Primorsk, Leningrad Oblast"],
["Приморско-Ахтарск, Краснодарский край "," Primorsko-Akhtarsk, Krasnodar Krai"],
["Приозерск, Ленинградская область "," Priozersk, Leningrad Oblast"],
["Прокопьевск, Кемеровская область "," Prokopyevsk, Kemerovo Oblast"],
["Пролетарск, Ростовская область "," Proletarsk, Rostov Oblast"],
["Протвино, Московская область "," Protvino, Moscow Oblast"],
["Прохладный, Кабардино-Балкарская Республика "," Prokhladny, Kabardino-Balkar Republic"],
["Псков, Псковская область "," Pskov, Pskov Oblast"],
["Пугачёв, Саратовская область "," Pugachyov, Saratov Oblast"],
["Пудож, Республика Карелия "," Pudozh, Republic of Karelia"],
["Пустошка, Псковская область "," Pustoshka, Pskov Oblast"],
["Пучеж, Ивановская область "," Puchezh, Ivanovo Oblast"],
["Пушкино, Московская область "," Pushkino, Moscow Oblast"],
["Пущино, Московская область "," Pushchino, Moscow Oblast"],
["Пыталово, Псковская область "," Pytalovo, Pskov Oblast"],
["Пыть-Ях, Ханты-Мансийский автономный округ "," Pyt-Yakh, Khanty-Mansi Autonomous Okrug"],
["Пятигорск, Ставропольский край "," Pyatigorsk, Stavropol Krai"],
["РРадужный, Владимирская область "," Raduzhny, Vladimir Oblast"],
["Радужный, Ханты-Мансийский автономный округ "," Raduzhny, Khanty-Mansi Autonomous Okrug"],
["Райчихинск, Амурская область "," Raychikhinsk, Amur Oblast"],
["Раменское, Московская область "," Ramenskoye, Moscow Oblast"],
["Рассказово, Тамбовская область "," Rasskazovo, Tambov Oblast"],
["Ревда, Свердловская область "," Revda, Sverdlovsk Oblast"],
["Реж, Свердловская область "," Rezh, Sverdlovsk Oblast"],
["Реутов, Московская область "," Reutov, Moscow Oblast"],
["Ржев, Тверская область "," Rzhev, Tver Oblast"],
["Родники, Ивановская область "," Rodniki, Ivanovo Oblast"],
["Рославль, Смоленская область "," Roslavl, Smolensk Oblast"],
["Россошь, Воронежская область "," Rossosh, Voronezh Oblast"],
["Ростов-на-Дону, Ростовская область "," Rostov-on-Don, Rostov Oblast"],
["Ростов, Ярославская область "," Rostov, Yaroslavl Oblast"],
["Рошаль, Московская область "," Roshal, Moscow Oblast"],
["Ртищево, Саратовская область "," Rtishchevo, Saratov Oblast"],
["Рубцовск, Алтайский край "," Rubtsovsk, Altai Krai"],
["Рудня, Смоленская область "," Rudnya, Smolensk Oblast"],
["Руза, Московская область "," Ruza, Moscow Oblast"],
["Рузаевка, Республика Мордовия "," Ruzayevka, Republic of Mordovia"],
["Рыбинск, Ярославская область "," Rybinsk, Yaroslavl Oblast"],
["Рыбное, Рязанская область "," Rybnoye, Ryazan Oblast"],
["Рыльск, Курская область "," Rylsk, Kursk Oblast"],
["Ряжск, Рязанская область "," Ryazhsk, Ryazan Oblast"],
["Рязань, Рязанская область "," Ryazan, Ryazan Oblast"],
["ССаки, Республика Крым "," Republic of Crimea"],
["Салават, Республика Башкортостан "," Salavat, Republic of Bashkortostan"],
["Салаир, Кемеровская область "," Salair, Kemerovo Oblast"],
["Салехард, Ямало-Ненецкий автономный округ "," Salekhard, Yamalo-Nenets Autonomous Okrug"],
["Сальск, Ростовская область "," Salsk, Rostov Oblast"],
["Самара, Самарская область "," Samara, Samara Oblast"],
["Санкт-Петербург "," Saint Petersburg"],
["Саранск, Республика Мордовия "," Saransk, Republic of Mordovia"],
["Сарапул, Удмуртская Республика "," Sarapul, Udmurt Republic"],
["Саратов, Саратовская область "," Saratov, Saratov Oblast"],
["Саров, Нижегородская область "," Sarov, Nizhny Novgorod Oblast"],
["Сасово, Рязанская область "," Sasovo, Ryazan Oblast"],
["Сатка, Челябинская область "," Satka, Chelyabinsk Oblast"],
["Сафоново, Смоленская область "," Safonovo, Smolensk Oblast"],
["Саяногорск, Республика Хакасия "," Sayanogorsk, Republic of Khakassia"],
["Саянск, Иркутская область "," Sayansk, Irkutsk Oblast"],
["Светлогорск, Калининградская область "," Svetlogorsk, Kaliningrad Oblast"],
["Светлоград, Ставропольский край "," Svetlograd, Stavropol Krai"],
["Светлый, Калининградская область "," Svetly, Kaliningrad Oblast"],
["Светогорск, Ленинградская область "," Svetogorsk, Leningrad Oblast"],
["Свирск, Иркутская область "," Svirsk, Irkutsk Oblast"],
["Свободный, Амурская область "," Svobodny, Amur Oblast"],
["Себеж, Псковская область "," Sebezh, Pskov Oblast"],
["Севастополь "," Sevastopol"],
["Северо-Курильск, Сахалинская область "," Severo-Kurilsk, Sakhalin Oblast"],
["Северобайкальск, Республика Бурятия "," Severobaykalsk, Republic of Buryatia"],
["Северодвинск, Архангельская область "," Severodvinsk, Arkhangelsk Oblast"],
["Североморск, Мурманская область "," Severomorsk, Murmansk Oblast"],
["Североуральск, Свердловская область "," Severouralsk, Sverdlovsk Oblast"],
["Северск, Томская область "," Seversk, Tomsk Oblast"],
["Севск, Брянская область "," Sevsk, Bryansk Oblast"],
["Сегежа, Республика Карелия "," Segezha, Republic of Karelia"],
["Сельцо, Брянская область "," Seltso, Bryansk Oblast"],
["Семёнов, Нижегородская область "," Semyonov, Nizhny Novgorod Oblast"],
["Семикаракорск, Ростовская область "," Semikarakorsk, Rostov Oblast"],
["Семилуки, Воронежская область "," Semiluki, Voronezh Oblast"],
["Сенгилей, Ульяновская область "," Sengiley, Ulyanovsk Oblast"],
["Серафимович, Волгоградская область "," Serafimovich, Volgograd Oblast"],
["Сергач, Нижегородская область "," Sergach, Nizhny Novgorod Oblast"],
["Сергиев Посад, Московская область "," Sergiyev Posad, Moscow Oblast"],
["Сердобск, Пензенская область "," Serdobsk, Penza Oblast"],
["Серов, Свердловская область "," Serov, Sverdlovsk Oblast"],
["Серпухов, Московская область "," Serpukhov, Moscow Oblast"],
["Сертолово, Ленинградская область "," Sertolovo, Leningrad Oblast"],
["Сибай, Республика Башкортостан "," Sibay, Republic of Bashkortostan"],
["Сим, Челябинская область "," Sim, Chelyabinsk Oblast"],
["Симферополь, Республика Крым "," Simferopol, Republic of Crimea"],
["Сковородино, Амурская область "," Skovorodino, Amur Oblast"],
["Скопин, Рязанская область "," Skopin, Ryazan Oblast"],
["Славгород, Алтайский край "," Slavgorod, Altai Krai"],
["Славск, Калининградская область "," Slavsk, Kaliningrad Oblast"],
["Славянск-на-Кубани, Краснодарский край "," Slavyansk-na-Kubani, Krasnodar Krai"],
["Сланцы, Ленинградская область "," Slantsy, Leningrad Oblast"],
["Слободской, Кировская область "," Slobodskoy, Kirov Oblast"],
["Слюдянка, Иркутская область "," Slyudyanka, Irkutsk Oblast"],
["Смоленск, Смоленская область "," Smolensk, Smolensk Oblast"],
["Снежинск, Челябинская область "," Snezhinsk, Chelyabinsk Oblast"],
["Снежногорск, Мурманская область "," Snezhnogorsk, Murmansk Oblast"],
["Собинка, Владимирская область "," Sobinka, Vladimir Oblast"],
["Советск, Калининградская область "," Sovetsk, Kaliningrad Oblast"],
["Советск, Кировская область "," Sovetsk, Kirov Oblast"],
["Советск, Тульская область "," Sovetsk, Tula Oblast"],
["Советская Гавань, Хабаровский край "," Sovetskaya Gavan, Khabarovsk Krai"],
["Советский, Ханты-Мансийский автономный округ "," Sovetsky, Khanty-Mansi Autonomous Okrug"],
["Сокол, Вологодская область "," Sokol, Vologda Oblast"],
["Солигалич, Костромская область "," Soligalich, Kostroma Oblast"],
["Соликамск, Пермский край "," Solikamsk, Perm Krai"],
["Солнечногорск, Московская область "," Solnechnogorsk, Moscow Oblast"],
["Соль-Илецк, Оренбургская область "," Sol-Iletsk, Orenburg Oblast"],
["Сольвычегодск, Архангельская область "," Solvychegodsk, Arkhangelsk Oblast"],
["Сольцы, Новгородская область "," Soltsy, Novgorod Oblast"],
["Сорочинск, Оренбургская область "," Sorochinsk, Orenburg Oblast"],
["Сорск, Республика Хакасия "," Sorsk, Republic of Khakassia"],
["Сортавала, Республика Карелия "," Sortavala, Republic of Karelia"],
["Сосенский, Калужская область "," Sosensky, Kaluga Oblast"],
["Сосновка, Кировская область "," Sosnovka, Kirov Oblast"],
["Сосновоборск, Красноярский край "," Sosnovoborsk, Krasnoyarsk Krai"],
["Сосновый Бор, Ленинградская область "," Sosnovy Bor, Leningrad Oblast"],
["Сосногорск, Республика Коми "," Sosnogorsk, Komi Republic"],
["Сочи, Краснодарский край "," Sochi, Krasnodar Krai"],
["Спас-Деменск, Калужская область "," Spas-Demensk, Kaluga Oblast"],
["Спас-Клепики, Рязанская область "," Spas-Klepiki, Ryazan Oblast"],
["Спасск, Пензенская область "," Spassk, Penza Oblast"],
["Спасск-Дальний, Приморский край "," Spassk-Dalny, Primorsky Krai"],
["Спасск-Рязанский, Рязанская область "," Spassk-Ryazansky, Ryazan Oblast"],
["Среднеколымск, Республика Саха "," Srednekolymsk, Sakha Republic"],
["Среднеуральск, Свердловская область "," Sredneuralsk, Sverdlovsk Oblast"],
["Сретенск, Забайкальский край "," Sretensk, Zabaykalsky Krai"],
["Ставрополь, Ставропольский край "," Stavropol, Stavropol Krai"],
["Старая Купавна, Московская область "," Staraya Kupavna, Moscow Oblast"],
["Старая Русса, Новгородская область "," Staraya Russa, Novgorod Oblast"],
["Старица, Тверская область "," Staritsa, Tver Oblast"],
["Стародуб, Брянская область "," Starodub, Bryansk Oblast"],
["Старый Крым, Республика Крым "," Stary Krym, Republic of Crimea"],
["Старый Оскол, Белгородская область "," Stary Oskol, Belgorod Oblast"],
["Стерлитамак, Республика Башкортостан "," Sterlitamak, Republic of Bashkortostan"],
["Стрежевой, Томская область "," Strezhevoy, Tomsk Oblast"],
["Строитель, Белгородская область "," Stroitel, Belgorod Oblast"],
["Струнино, Владимирская область "," Strunino, Vladimir Oblast"],
["Ступино, Московская область "," Stupino, Moscow Oblast"],
["Суворов, Тульская область "," Suvorov, Tula Oblast"],
["Судак, Республика Крым "," Sudak, Republic of Crimea"],
["Суджа, Курская область "," Sudzha, Kursk Oblast"],
["Судогда, Владимирская область "," Sudogda, Vladimir Oblast"],
["Суздаль, Владимирская область "," Suzdal, Vladimir Oblast"],
["Суоярви, Республика Карелия "," Suoyarvi, Republic of Karelia"],
["Сураж, Брянская область "," Surazh, Bryansk Oblast"],
["Сургут, Ханты-Мансийский автономный округ "," Surgut, Khanty-Mansi Autonomous Okrug"],
["Суровикино, Волгоградская область "," Surovikino, Volgograd Oblast"],
["Сурск, Пензенская область "," Sursk, Penza Oblast"],
["Сусуман, Магаданская область "," Susuman, Magadan Oblast"],
["Сухиничи, Калужская область "," Sukhinichi, Kaluga Oblast"],
["Сухой Лог, Свердловская область "," Sukhoy Log, Sverdlovsk Oblast"],
["Сызрань, Самарская область "," Syzran, Samara Oblast"],
["Сыктывкар, Республика Коми "," Syktyvkar, Komi Republic"],
["Сысерть, Свердловская область "," Sysert, Sverdlovsk Oblast"],
["Сычёвка, Смоленская область "," Sychyovka, Smolensk Oblast"],
["Сясьстрой, Ленинградская область "," Syasstroy, Leningrad Oblast"],
["ТТавда, Свердловская область "," Tavda, Sverdlovsk Oblast"],
["Таганрог, Ростовская область "," Taganrog, Rostov Oblast"],
["Тайга, Кемеровская область "," Tayga, Kemerovo Oblast"],
["Тайшет, Иркутская область "," Tayshet, Irkutsk Oblast"],
["Талдом, Московская область "," Taldom, Moscow Oblast"],
["Талица, Свердловская область "," Talitsa, Sverdlovsk Oblast"],
["Тамбов, Тамбовская область "," Tambov, Tambov Oblast"],
["Тара, Омская область "," Tara, Omsk Oblast"],
["Тарко-Сале, Ямало-Ненецкий автономный округ "," Tarko-Sale, Yamalo-Nenets Autonomous Okrug"],
["Таруса, Калужская область "," Tarusa, Kaluga Oblast"],
["Татарск, Новосибирская область "," Tatarsk, Novosibirsk Oblast"],
["Таштагол, Кемеровская область "," Tashtagol, Kemerovo Oblast"],
["Тверь, Тверская область "," Tver, Tver Oblast"],
["Теберда, Карачаево-Черкесская Республика "," Teberda, Karachay-Cherkess Republic"],
["Тейково, Ивановская область "," Teykovo, Ivanovo Oblast"],
["Темников, Республика Мордовия "," Temnikov, Republic of Mordovia"],
["Темрюк, Краснодарский край "," Temryuk, Krasnodar Krai"],
["Терек, Кабардино-Балкарская Республика "," Terek, Kabardino-Balkar Republic"],
["Тетюши, Республика Татарстан "," Tetyushi, Republic of Tatarstan"],
["Тимашёвск, Краснодарский край "," Timashyovsk, Krasnodar Krai"],
["Тихвин, Ленинградская область "," Tikhvin, Leningrad Oblast"],
["Тихорецк, Краснодарский край "," Tikhoretsk, Krasnodar Krai"],
["Тобольск, Тюменская область "," Tobolsk, Tyumen Oblast"],
["Тогучин, Новосибирская область "," Toguchin, Novosibirsk Oblast"],
["Тольятти, Самарская область "," Tolyatti, Samara Oblast"],
["Томари, Сахалинская область "," Tomari, Sakhalin Oblast"],
["Томмот, Республика Саха "," Tommot, Sakha Republic"],
["Томск, Томская область "," Tomsk, Tomsk Oblast"],
["Топки, Кемеровская область "," Topki, Kemerovo Oblast"],
["Торжок, Тверская область "," Torzhok, Tver Oblast"],
["Торопец, Тверская область "," Toropets, Tver Oblast"],
["Тосно, Ленинградская область "," Tosno, Leningrad Oblast"],
["Тотьма, Вологодская область "," Totma, Vologda Oblast"],
["Трёхгорный, Челябинская область "," Tryokhgorny, Chelyabinsk Oblast"],
["Троицк, Челябинская область "," Troitsk, Chelyabinsk Oblast"],
["Трубчевск, Брянская область "," Trubchevsk, Bryansk Oblast"],
["Туапсе, Краснодарский край "," Tuapse, Krasnodar Krai"],
["Туймазы, Республика Башкортостан "," Tuymazy, Republic of Bashkortostan"],
["Тула, Тульская область "," Tula, Tula Oblast"],
["Тулун, Иркутская область "," Tulun, Irkutsk Oblast"],
["Туран, Республика Тыва "," Turan, Tuva Republic"],
["Туринск, Свердловская область "," Turinsk, Sverdlovsk Oblast"],
["Тутаев, Ярославская область "," Tutayev, Yaroslavl Oblast"],
["Тында, Амурская область "," Tynda, Amur Oblast"],
["Тырныауз, Кабардино-Балкарская Республика "," Tyrnyauz, Kabardino-Balkar Republic"],
["Тюкалинск, Омская область "," Tyukalinsk, Omsk Oblast"],
["Тюмень, Тюменская область "," Tyumen, Tyumen Oblast"],
["Уварово, Тамбовская область "," Uvarovo, Tambov Oblast"],
["Углегорск, Сахалинская область "," Uglegorsk, Sakhalin Oblast"],
["Углич, Ярославская область "," Uglich, Yaroslavl Oblast"],
["Удачный, Республика Саха "," Udachny, Sakha Republic"],
["Удомля, Тверская область "," Udomlya, Tver Oblast"],
["Ужур, Красноярский край "," Uzhur, Krasnoyarsk Krai"],
["Узловая, Тульская область "," Uzlovaya, Tula Oblast"],
["Улан-Удэ, Республика Бурятия "," Ulan-Ude, Republic of Buryatia"],
["Ульяновск, Ульяновская область "," Ulyanovsk, Ulyanovsk Oblast"],
["Унеча, Брянская область "," Unecha, Bryansk Oblast"],
["Урай, Ханты-Мансийский автономный округ "," Uray, Khanty-Mansi Autonomous Okrug"],
["Урень, Нижегородская область "," Uren, Nizhny Novgorod Oblast"],
["Уржум, Кировская область "," Urzhum, Kirov Oblast"],
["Урус-Мартан, Чеченская Республика "," Urus-Martan"],
["Урюпинск, Волгоградская область "," Uryupinsk, Volgograd Oblast"],
["Усинск, Республика Коми "," Usinsk, Komi Republic"],
["Усмань, Липецкая область "," Usman, Lipetsk Oblast"],
["Усолье-Сибирское, Иркутская область "," Usolye-Sibirskoye, Irkutsk Oblast"],
["Усолье, Пермский край "," Usolye, Perm Krai"],
["Уссурийск, Приморский край "," Ussuriysk, Primorsky Krai"],
["Усть-Джегута, Карачаево-Черкесская Республика "," Ust-Dzheguta, Karachay-Cherkess Republic"],
["Усть-Илимск, Иркутская область "," Ust-Ilimsk, Irkutsk Oblast"],
["Усть-Катав, Челябинская область "," Ust-Katav, Chelyabinsk Oblast"],
["Усть-Кут, Иркутская область "," Ust-Kut, Irkutsk Oblast"],
["Усть-Лабинск, Краснодарский край "," Ust-Labinsk, Krasnodar Krai"],
["Устюжна, Вологодская область "," Ustyuzhna, Vologda Oblast"],
["Уфа, Республика Башкортостан "," Ufa, Republic of Bashkortostan"],
["Ухта, Республика Коми "," Ukhta, Komi Republic"],
["Учалы, Республика Башкортостан "," Uchaly, Republic of Bashkortostan"],
["Уяр, Красноярский край "," Uyar, Krasnoyarsk Krai"],
["Фатеж, Курская область "," Fatezh, Kursk Oblast"],
["Феодосия, Республика Крым "," Feodosia, Republic of Crimea"],
["Фокино, Брянская область "," Fokino, Bryansk Oblast"],
["Фокино, Приморский край "," Fokino, Primorsky Krai"],
["Фролово, Волгоградская область "," Frolovo, Volgograd Oblast"],
["Фрязино, Московская область "," Fryazino, Moscow Oblast"],
["Фурманов, Ивановская область "," Furmanov, Ivanovo Oblast"],
["Хабаровск, Хабаровский край "," Khabarovsk, Khabarovsk Krai"],
["Хадыженск, Краснодарский край "," Khadyzhensk, Krasnodar Krai"],
["Ханты-Мансийск, Ханты-Мансийский автономный округ "," Khanty-Mansiysk, Khanty-Mansi Autonomous Okrug"],
["Харабали, Астраханская область "," Kharabali, Astrakhan Oblast"],
["Харовск, Вологодская область "," Kharovsk, Vologda Oblast"],
["Хасавюрт, Республика Дагестан "," Khasavyurt, Republic of Dagestan"],
["Хвалынск, Саратовская область "," Khvalynsk, Saratov Oblast"],
["Хилок, Забайкальский край "," Khilok, Zabaykalsky Krai"],
["Химки, Московская область "," Khimki, Moscow Oblast"],
["Холм, Новгородская область "," Kholm, Novgorod Oblast"],
["Холмск, Сахалинская область "," Kholmsk, Sakhalin Oblast"],
["Хотьково, Московская область "," Khotkovo, Moscow Oblast"],
["Цивильск, Чувашская Республика "," Tsivilsk, Chuvash Republic"],
["Цимлянск, Ростовская область "," Tsimlyansk, Rostov Oblast"],
["Чадан, Республика Тыва "," Chadan, Tuva Republic"],
["Чайковский, Пермский край "," Chaykovsky, Perm Krai"],
["Чапаевск, Самарская область "," Chapayevsk, Samara Oblast"],
["Чаплыгин, Липецкая область "," Chaplygin, Lipetsk Oblast"],
["Чебаркуль, Челябинская область "," Chebarkul, Chelyabinsk Oblast"],
["Чебоксары, Чувашская Республика "," Cheboksary, Chuvash Republic"],
["Чегем, Кабардино-Балкарская Республика "," Chegem, Kabardino-Balkar Republic"],
["Чекалин, Тульская область "," Chekalin, Tula Oblast"],
["Челябинск, Челябинская область "," Chelyabinsk, Chelyabinsk Oblast"],
["Чердынь, Пермский край "," Cherdyn, Perm Krai"],
["Черемхово, Иркутская область "," Cheremkhovo, Irkutsk Oblast"],
["Черепаново, Новосибирская область "," Cherepanovo, Novosibirsk Oblast"],
["Череповец, Вологодская область "," Cherepovets, Vologda Oblast"],
["Черкесск, Карачаево-Черкесская Республика "," Cherkessk, Karachay-Cherkess Republic"],
["Чёрмоз, Пермский край "," Chyormoz, Perm Krai"],
["Черноголовка, Московская область "," Chernogolovka, Moscow Oblast"],
["Черногорск, Республика Хакасия "," Chernogorsk, Republic of Khakassia"],
["Чернушка, Пермский край "," Chernushka, Perm Krai"],
["Черняховск, Калининградская область "," Chernyakhovsk, Kaliningrad Oblast"],
["Чехов, Московская область "," Chekhov, Moscow Oblast"],
["Чистополь, Республика Татарстан "," Chistopol, Republic of Tatarstan"],
["Чита, Забайкальский край "," Chita, Zabaykalsky Krai"],
["Чкаловск, Нижегородская область "," Chkalovsk, Nizhny Novgorod Oblast"],
["Чудово, Новгородская область "," Chudovo, Novgorod Oblast"],
["Чулым, Новосибирская область "," Chulym, Novosibirsk Oblast"],
["Чусовой, Пермский край "," Chusovoy, Perm Krai"],
["Чухлома, Костромская область "," Chukhloma, Kostroma Oblast"],
["Шагонар, Республика Тыва "," Shagonar, Tuva Republic"],
["Шадринск, Курганская область "," Shadrinsk, Kurgan Oblast"],
["Шали, Чеченская Республика "," Shali, Chechen Republic"],
["Шарыпово, Красноярский край "," Sharypovo, Krasnoyarsk Krai"],
["Шарья, Костромская область "," Sharya, Kostroma Oblast"],
["Шатура, Московская область "," Shatura, Moscow Oblast"],
["Шахты, Ростовская область "," Shakhty, Rostov Oblast"],
["Шахунья, Нижегородская область "," Shakhunya, Nizhny Novgorod Oblast"],
["Шацк, Рязанская область "," Shatsk, Ryazan Oblast"],
["Шебекино, Белгородская область "," Shebekino, Belgorod Oblast"],
["Шелехов, Иркутская область "," Shelekhov, Irkutsk Oblast"],
["Шенкурск, Архангельская область "," Shenkursk, Arkhangelsk Oblast"],
["Шилка, Забайкальский край "," Shilka, Zabaykalsky Krai"],
["Шимановск, Амурская область "," Shimanovsk, Amur Oblast"],
["Шиханы, Саратовская область "," Shikhany, Saratov Oblast"],
["Шлиссельбург, Ленинградская область "," Shlisselburg, Leningrad Oblast"],
["Шумерля, Чувашская Республика "," Shumerlya, Chuvash Republic"],
["Шумиха, Курганская область "," Shumikha, Kurgan Oblast"],
["Шуя, Ивановская область "," Shuya, Ivanovo Oblast"],
["Щёкино, Тульская область "," Shchyokino, Tula Oblast"],
["Щёлкино, Республика Крым "," Shchelkino, Republic of Crimea"],
["Щёлково, Московская область "," Shchyolkovo, Moscow Oblast"],
["Щигры, Курская область "," Shchigry, Kursk Oblast"],
["Щучье, Курганская область "," Shchuchye, Kurgan Oblast"],
["Электрогорск, Московская область "," Elektrogorsk, Moscow Oblast"],
["Электросталь, Московская область "," Elektrostal, Moscow Oblast"],
["Электроугли, Московская область "," Elektrougli, Moscow Oblast"],
["Элиста, Республика Калмыкия "," Elista, Republic of Kalmykia"],
["Энгельс, Саратовская область "," Engels, Saratov Oblast"],
["Эртиль, Воронежская область "," Ertil, Voronezh Oblast"],
["Югорск, Ханты-Мансийский автономный округ "," Yugorsk, Khanty-Mansi Autonomous Okrug"],
["Южа, Ивановская область "," Yuzha, Ivanovo Oblast"],
["Южно-Сахалинск, Сахалинская область "," Yuzhno-Sakhalinsk, Sakhalin Oblast"],
["Южно-Сухокумск, Республика Дагестан "," Yuzhno-Sukhokumsk, Republic of Dagestan"],
["Южноуральск, Челябинская область "," Yuzhnouralsk, Chelyabinsk Oblast"],
["Юрга, Кемеровская область "," Yurga, Kemerovo Oblast"],
["Юрьев-Польский, Владимирская область "," Yuryev-Polsky, Vladimir Oblast"],
["Юрьевец, Ивановская область "," Yuryevets, Ivanovo Oblast"],
["Юрюзань, Челябинская область "," Yuryuzan, Chelyabinsk Oblast"],
["Юхнов, Калужская область "," Yukhnov, Kaluga Oblast"],
["Ядрин, Чувашская Республика "," Yadrin, Chuvash Republic"],
["Якутск, Республика Саха "," Yakutsk, Sakha Republic"],
["Ялта, Республика Крым "," Yalta, Republic of Crimea"],
["Ялуторовск, Тюменская область "," Yalutorovsk, Tyumen Oblast"],
["Янаул, Республика Башкортостан "," Yanaul, Republic of Bashkortostan"],
["Яранск, Кировская область "," Yaransk, Kirov Oblast"],
["Яровое, Алтайский край "," Yarovoye, Altai Krai"],
["Ярославль, Ярославская область "," Yaroslavl, Yaroslavl Oblast"],
["Ярцево, Смоленская область "," Yartsevo, Smolensk Oblast"],
["Ясногорск, Тульская область "," Yasnogorsk, Tula Oblast"],
["Ясный, Оренбургская область "," Yasny, Orenburg Oblast"],
["Яхрома, Московская область "," Yakhroma, Moscow Oblast"],]